version: '3.8'

services:
  notebooks:
    image: ghcr.io/hes-xplain/notebooks:latest
    ports:
    - "8080:8080"
    - "8888:8888"
    networks:
    - default

networks:
  default:
    name: nat
    external: true
