services:
  notebooks:
    image: ghcr.io/hes-xplain/notebooks:latest
    ports:
    - "8080:8080"
    - "8888:8888"
    networks:
    - default
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  default:
    name: nat
